---
# tasks file for gitlab
- name: Install dependencies for gitlab
  apt: name={{item}} state=present
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix

- name: Download gitlab installer
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: 0770

- name: Execute gitlab installer >> /.gitlab-installer.log
  shell: /tmp/script.deb.sh
  become: true
  args:
    creates: /.gitlab-installer.log

- name: Install gitlab-ce
  apt: name=gitlab-ce state=present

- name: Place gitlab.rb config file
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    mode: '0600'

- name: Reconfigure gitlab
  command: /usr/bin/gitlab-ctl reconfigure

- name: Place cron.d file for regular backups
  template:
    src: cron.j2
    dest: /etc/cron.d/gitlab
    owner: root
    mode: '0700'